const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log("Languages array:", languages);
let firstElement = languages[0];
console.log('The first element of the array is', firstElement);
let thirdElement = languages[2];
console.log('The third element of the array is', thirdElement);
let length = languages.length;
console.log('The length of the array is', length);
let lastElement = languages[length - 1];
console.log('The last element of the array is', lastElement);
